=== strohitv/ddtunit-fork/src/main/resources/junitx/ddtunit/data/processing/parser/ddtunit.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 elementFormDefault="qualified" attributeFormDefault="unqualified">
 <xsd:element name="ddtunit">
  <xsd:annotation>
   <xsd:documentation>Schema for DDTUnit test data</xsd:documentation>
  </xsd:annotation>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element name="resources" type="objSetType" minOccurs="0" maxOccurs="1" />
    <xsd:sequence minOccurs="1" maxOccurs="unbounded">
     <xsd:element ref="cluster" />
    </xsd:sequence>
   </xsd:sequence>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name="cluster">
  <xsd:complexType>
   <xsd:annotation>
    <xsd:documentation>
     cluster contains multiple groups of tests
    </xsd:documentation>
   </xsd:annotation>
   <xsd:sequence>
    <xsd:element ref="description" minOccurs="0" maxOccurs="1" />
    <xsd:element name="objs" type="objSetType" minOccurs="0" maxOccurs="1" />
    <xsd:sequence minOccurs="0" maxOccurs="unbounded">
     <xsd:element name="group">
      <xsd:complexType>
       <xsd:complexContent>
        <xsd:extension base="groupType">
         <xsd:attribute name="id" type="xsd:string" use="required" />
        </xsd:extension>
       </xsd:complexContent>
      </xsd:complexType>
     </xsd:element>
    </xsd:sequence>
   </xsd:sequence>
   <xsd:attribute name="id" type="xsd:string" use="required" />
  </xsd:complexType>
 </xsd:element>

 <xsd:complexType name="groupType">
  <xsd:annotation>
   <xsd:documentation>
    group containing multiple test definitions
   </xsd:documentation>
  </xsd:annotation>
  <xsd:sequence minOccurs="0" maxOccurs="unbounded">
   <xsd:element ref="test" />
  </xsd:sequence>
 </xsd:complexType>

 <xsd:element name="test">
  <xsd:annotation>
   <xsd:documentation>
    Definition of object element used for mapping to objects of test framework
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexType>
   <xsd:annotation>
    <xsd:documentation>
     test contains set of objects and/or set of asserts
    </xsd:documentation>
   </xsd:annotation>
   <xsd:sequence>
    <xsd:element name="objs" type="objSetType" minOccurs="0" />
    <xsd:element name="asserts" type="assertSetType" minOccurs="0" />
   </xsd:sequence>
   <xsd:attribute name="id" type="xsd:string" use="required" />
  </xsd:complexType>
 </xsd:element>

 <xsd:complexType name="objSetType">
  <xsd:annotation>
   <xsd:documentation>
    Definition of set of object elements used for mapping to Java Object
    instance
   </xsd:documentation>
  </xsd:annotation>
  <xsd:sequence minOccurs="0" maxOccurs="unbounded">
   <xsd:element ref="obj" />
  </xsd:sequence>
 </xsd:complexType>

 <xsd:complexType name="assertSetType">
  <xsd:annotation>
   <xsd:documentation>
    Definition of assert element used for Java objects containing all
    information about asserts to process
   </xsd:documentation>
  </xsd:annotation>
  <xsd:sequence minOccurs="0" maxOccurs="unbounded">
   <xsd:sequence>
    <xsd:element ref="assert" minOccurs="0" />
    <xsd:element ref="exception" minOccurs="0" />
   </xsd:sequence>
  </xsd:sequence>
 </xsd:complexType>

 <xsd:simpleType name="objectAssertType">
  <xsd:restriction base="xsd:string">
   <xsd:enumeration value="isTrue" />
   <xsd:enumeration value="isFalse" />
   <xsd:enumeration value="isEqual" />
   <xsd:enumeration value="isNotEqual" />
   <xsd:enumeration value="isSame" />
   <xsd:enumeration value="isNotSame" />
   <xsd:enumeration value="isNull" />
   <xsd:enumeration value="isNotNull" />
   <xsd:enumeration value="isGT" />
   <xsd:enumeration value="isNotGT" />
   <xsd:enumeration value="isLT" />
   <xsd:enumeration value="isNotLT" />
   <xsd:enumeration value="isInRange" />
   <xsd:enumeration value="isNotInRange" />
   <xsd:enumeration value="isContainedIn" />
   <xsd:enumeration value="isNotContainedIn" />
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:simpleType name="exceptionAssertType">
  <xsd:restriction base="xsd:string">
   <xsd:enumeration value="isEqual" />
   <xsd:enumeration value="isSimilar" />
   <xsd:enumeration value="isInstanceOf" />
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:simpleType name="hintType">
  <xsd:restriction base="xsd:string">
   <xsd:enumeration value="fields" />
   <xsd:enumeration value="collection" />
   <xsd:enumeration value="map" />
   <xsd:enumeration value="constant" />
   <xsd:enumeration value="constructor" />
   <xsd:enumeration value="call" />
   <xsd:enumeration value="date" />
   <xsd:enumeration value="bean" />
   <xsd:enumeration value="array" />
  </xsd:restriction>
 </xsd:simpleType>


 <xsd:complexType name="anyType">
  <xsd:sequence minOccurs="0" maxOccurs="unbounded">
   <xsd:any namespace="##any" processContents="skip" />
  </xsd:sequence>
 </xsd:complexType>

 <xsd:element name="description" type="xsd:string" />

 <xsd:element name="obj">
  <xsd:annotation>
   <xsd:documentation>
    Definition of object element used for mapping to objects of test framework
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexType mixed="true">
   <xsd:sequence minOccurs="0" maxOccurs="unbounded">
    <xsd:any namespace="##any" processContents="skip" />
   </xsd:sequence>
   <xsd:attributeGroup ref="objAttributes" />
  </xsd:complexType>
 </xsd:element>

 <xsd:attributeGroup name="objAttributes">
  <xsd:attribute name="id" type="xsd:string" use="required" />
  <xsd:attribute name="type" type="xsd:string" use="required" />
  <xsd:attribute name="hint" type="hintType" use="optional" default="fields" />
  <xsd:attribute name="keytype" type="xsd:string" use="optional"
   default="string" />
  <xsd:attribute name="valuetype" type="xsd:string" use="optional"
   default="string" />
  <xsd:attribute name="method" type="xsd:string" use="optional"
   default="constructor" />
  <xsd:attribute name="refid" type="xsd:string" use="optional" />
  <xsd:attribute name="calltype" type="xsd:string" use="optional" />
  <xsd:attribute name="dateformat" type="xsd:string" />
  <xsd:attribute name="locale" type="xsd:string" />
    </xsd:attributeGroup>

 <xsd:element name="assert">
  <xsd:annotation>
   <xsd:documentation>
    Definition of assert/exception element used for mapping to assert objects of
    test framework
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexType mixed="true">
   <xsd:sequence minOccurs="0" maxOccurs="unbounded">
    <xsd:any namespace="##any" processContents="skip" />
   </xsd:sequence>
   <xsd:attributeGroup ref="assertAttributes" />
  </xsd:complexType>
 </xsd:element>

 <xsd:attributeGroup name="assertAttributes">
  <xsd:attributeGroup ref="objAttributes" />
  <xsd:attribute name="action" type="objectAssertType" use="required" />
 </xsd:attributeGroup>

 <xsd:element name="exception">
  <xsd:annotation>
   <xsd:documentation>
    Definition of exception element used for mapping to assert objects on
    expected exceptions of test framework
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexType mixed="true">
   <xsd:sequence minOccurs="0" maxOccurs="unbounded">
    <xsd:any namespace="##any" processContents="skip" />
   </xsd:sequence>
   <xsd:attributeGroup ref="exceptionAttributes" />
  </xsd:complexType>
 </xsd:element>

 <xsd:attributeGroup name="exceptionAttributes">
  <xsd:attributeGroup ref="objAttributes" />
  <xsd:attribute name="action" type="exceptionAssertType" use="required" />
 </xsd:attributeGroup>

</xsd:schema>

=== strohitv/ddtunit-fork/src/test/resources/junitx/ddtunit/DDT-ExecutionResultTest.xml
<?xml version="1.0"  encoding="ISO-8859-1"?>
<ddtunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="http://ddtunit.sourceforge.net/ddtunit.xsd">
  <cluster id="ExecutionResultNoProblem">
    <group id="testThreeTestsNoProblem">
      <test id="my-first-testcase">
        <objs>
          <obj id="objId"  type="java.lang.String">my-first-testcase</obj>
        </objs>
      </test>
      <test id="my-second-testcase">
        <objs>
          <obj id="objId"  type="java.lang.String">my-second-testcase</obj>
        </objs>
      </test>
      <test id="my-third-testcase">
        <objs>
          <obj id="objId"  type="java.lang.String">my-third-testcase</obj>
        </objs>
      </test>
    </group>
    <!--                                                                    -->
    <!--                                                                    -->
    <!--                                                                    -->
    <group id="testThreeTestsOneAssertFailed">
      <test id="my-first-testcase">
        <objs>
          <obj id="objId"  type="java.lang.String">my-first-testcase</obj>
        </objs>
        <asserts>
          <assert id="result"  type="java.lang.String" action="isEqual">my-first-testcase</assert>
        </asserts>
      </test>
      <test id="my-second-testcase">
        <objs>
          <obj id="objId"  type="java.lang.String">my-second-testcase</obj>
        </objs>
        <asserts>
          <assert id="result" type="java.lang.String" action="isEqual">my-unexpected-testcase</assert>
        </asserts>
      </test>
      <test id="my-third-testcase">
        <objs>
          <obj id="objId"  type="java.lang.String">my-third-testcase</obj>
        </objs>
        <asserts>
          <assert id="result"  type="java.lang.String" action="isEqual">my-third-testcase</assert>
        </asserts>
      </test>
    </group>
    <!--                                                                    -->
    <!--                                                                    -->
    <!--                                                                    -->
    <group id="testThreeTestsOneAssertFailedOneException">
      <test id="my-first-testcase">
        <objs>
          <obj id="objId"  type="java.lang.String">my-first-testcase</obj>
        </objs>
        <asserts>
          <assert id="result"  type="java.lang.String" action="isEqual">my-first-testcase</assert>
        </asserts>
      </test>
      <test id="my-second-testcase">
        <objs>
          <obj id="objId"  type="java.lang.String">my-second-testcase</obj>
        </objs>
        <asserts>
          <assert id="result" type="java.lang.String" action="isEqual">my-unexpected-testcase</assert>
        </asserts>
      </test>
      <test id="my-third-testcase">
        <objs>
          <obj id="objId"  type="java.lang.String">my-third-testcase</obj>
        </objs>
        <asserts>
          <assert id="result"  type="java.lang.String" action="isEqual">my-third-testcase</assert>
        </asserts>
      </test>
    </group>
  </cluster>
</ddtunit>

=== strohitv/ddtunit-fork/src/test/resources/junitx/ddtunit/functest/DDT-ProcessComparableDataTest.xml
<?xml version="1.0" ?>
<ddtunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="http://ddtunit.sourceforge.net/ddtunit.xsd">
  <cluster id="ProcessComparableDataTest">
  <!--                                                                  -->
  <!-- java.util.Date                                                   -->
  <!--                                                                  -->
    <group id="testComparableType">
      <test id="LongIsGT">
		<objs><obj id="myComparable" type="long">4711</obj></objs>
		<asserts><assert id="result" type="long" action="isGT">4700</assert></asserts>
	  </test>
      <test id="LongIsNotGT">
		<objs><obj id="myComparable" type="long">4711</obj></objs>
		<asserts><assert id="result" type="long" action="isNotGT">4712</assert></asserts>
	  </test>
      <test id="LongIsLT">
		<objs><obj id="myComparable" type="long">4711</obj></objs>
		<asserts><assert id="result" type="long" action="isLT">4747</assert></asserts>
	  </test>
      <test id="LongIsNotLT">
		<objs><obj id="myComparable" type="long">4711</obj></objs>
		<asserts><assert id="result" type="long" action="isNotLT">4712</assert></asserts>
	  </test>
    <test id="LongIsInRange">
      <objs><obj id="myComparable" type="long">4711</obj></objs>
      <asserts><assert id="result" type="range" action="isInRange">
        <start type="long">4700</start>
        <end type="long">4759</end>
      </assert></asserts>
   </test>
    <test id="LongIsInRangeOnStart">
      <objs><obj id="myComparable" type="long">4711</obj></objs>
      <asserts><assert id="result" type="range" action="isInRange">
        <start type="long">4711</start>
        <end type="long">4759</end>
      </assert></asserts>
   </test>
    <test id="LongIsInRangeOnExcludedStart">
      <objs><obj id="myComparable" type="long">4711</obj></objs>
      <asserts>
        <exception id="expected" type="junit.framework.AssertionFailedError"
          action="isSimilar">not in Range</exception>
        <assert id="result" type="range" action="isInRange">
          <startIncluded>false</startIncluded>
          <start type="long">4711</start>
          <end type="long">4759</end>
      </assert></asserts>
   </test>
    <test id="LongIsInRangeOnExcludedEnd">
      <objs><obj id="myComparable" type="long">4759</obj></objs>
      <asserts>
        <exception id="expected" type="junit.framework.AssertionFailedError"
          action="isSimilar">not in Range</exception>
        <assert id="result" type="range" action="isInRange">
          <startIncluded>false</startIncluded>
          <start type="long">4711</start>
          <endIncluded>false</endIncluded>
          <end type="long">4759</end>
      </assert></asserts>
   </test>
    <test id="LongIsInRangeOnEnd">
      <objs><obj id="myComparable" type="long">4759</obj></objs>
      <asserts><assert id="result" type="range" action="isInRange">
        <start type="long">4711</start>
        <end type="long">4759</end>
      </assert></asserts>
   </test>
    <test id="LongIsInRangeExternalValue">
      <objs><obj id="myComparable" type="long">4859</obj></objs>
      <asserts>
        <exception id="expected" type="junit.framework.AssertionFailedError" 
          action="isSimilar">not in Range</exception>
        <assert id="result" type="range" action="isInRange">
        <start type="long">4711</start>
        <end type="long">4759</end>
      </assert></asserts>
   </test>
	  <!--                                                                 -->
	  <!--                                                                 -->
	  <!--                                                                 -->
      <test id="DoubleIsGT">
		<objs><obj id="myComparable" type="double">47.11</obj></objs>
		<asserts><assert id="result" type="double" action="isGT">47.00</assert></asserts>
	  </test>
      <test id="DoubleIsNotGT">
		<objs><obj id="myComparable" type="double">47.11</obj></objs>
		<asserts><assert id="result" type="double" action="isNotGT">4712</assert></asserts>
	  </test>
      <test id="DoubleIsLT">
		<objs><obj id="myComparable" type="double">47.11</obj></objs>
		<asserts><assert id="result" type="double" action="isLT">47.47</assert></asserts>
	  </test>
      <test id="DoubleIsNotLT">
		<objs><obj id="myComparable" type="double">47.11</obj></objs>
		<asserts><assert id="result" type="double" action="isNotLT">47.12</assert></asserts>
	  </test>
	</group>
  </cluster>
</ddtunit>

=== strohitv/ddtunit-fork/src/test/resources/junitx/ddtunit/functest/DDT-ProcessMethodCallValuesTest.xml
<?xml version="1.0" ?>
<ddtunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="http://ddtunit.sourceforge.net/ddtunit.xsd">
  <cluster id="ProcessMethodCallValuesTest">
    <!--                                                                  -->
    <!-- instanciate object by constructor                                -->
    <!--                                                                  -->
    <group id="testCreateFromMethodCall">
      <test id="callStaticMethod">
        <objs>
          <obj id="myObj" type="junitx.ddtunit.resources.Currency" hint="call"
            method="getInstance">
            <item type="string">EUR</item>
          </obj>
        </objs>
        <asserts>
          <assert id="result" type="junitx.ddtunit.resources.Currency" hint="call"
            method="getInstance" action="isEqual">
            <item type="string">EUR</item>
          </assert>
        </asserts>
      </test>
      <test id="callPublicMethodOnObjectWithDefaultConstructor">
        <objs>
          <obj id="myObj" type="string" hint="call" 
            calltype="junitx.ddtunit.resources.SimpleVO" method="toString" />
        </objs>
        <asserts>
          <assert id="result" type="string" action="isEqual">
            SimpleVO:
  textValue="null"
  integerValue="null"
  doubleValue="null"
          </assert>
        </asserts>
      </test>
    </group>
  </cluster>
</ddtunit>

=== strohitv/ddtunit-fork/src/test/resources/DDT-XmlEntityTest.xml
<?xml version="1.0" ?>
<!DOCTYPE ddtunit [
  <!ENTITY % exEntity SYSTEM "DDT-XmlEntitySameDirTest.xml">
  <!ENTITY % exSubEntity SYSTEM "./junitx/ddtunit/resources/DDT-XmlEntitySubDirTest.xml">
  <!ENTITY % exAbsEntity SYSTEM "/DDT-XmlEntityAbsResourceTest.xml">
  %exEntity;
  %exSubEntity;
  %exAbsEntity;
]>
<ddtunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="http://ddtunit.sourceforge.net/ddtunit.xsd">
  <cluster id="XmlEntityTest">
    <!--                                                                  -->
    <!-- simple object retrieval                                          -->
    <!--                                                                  -->
    <group id="testReadExternalEntityParam">
      <test id="myFirstTestCase">
        <objs>
          <obj id="myparam" type="java.lang.String">&exparam;</obj>
        </objs>
        <asserts>
          <assert id="result" type="java.lang.String" action="isEqual">my4711String</assert>
        </asserts>
      </test>
      <test id="mySecondTestCase">
        <objs>
          <obj id="myparam" type="java.lang.String">&subparam;</obj>
        </objs>
        <asserts>
          <assert id="result" type="java.lang.String" action="isEqual">my0815String</assert>
        </asserts>
      </test>
    </group>
  </cluster>
</ddtunit>

=== strohitv/ddtunit-fork/src/test/resources/junitx/ddtunit/functest/DDT-ProcessExpectedExceptionTest.xml
<?xml version="1.0" ?>
<ddtunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="http://ddtunit.sourceforge.net/ddtunit.xsd">
  <cluster id="ProcessExpectedExceptionTest">
    <!--                                                                  -->
    <!-- simple exception processing                                      -->
    <!--                                                                  -->
    <group id="testProcessExpectedException">
      <test id="catchByIsEquals">
        <asserts>
          <exception id="expectedException" 
            type="junitx.ddtunit.DDTException" action="isEqual" hint="call">
            <item type="string">My own Exception</item></exception>
        </asserts>
      </test>
      <test id="catchByIsSimilar">
        <asserts>
          <exception id="expectedException" 
            type="junitx.ddtunit.DDTException" action="isSimilar" hint="call">
            <item type="string">My own</item></exception>
        </asserts>
      </test>
      <test id="catchByIsInstanceOf">
        <asserts>
          <exception id="expectedException" 
            type="java.lang.RuntimeException" action="isInstanceOf" />
        </asserts>
      </test>
    </group>
  </cluster>
  <cluster id="ProcessUnexpectedExceptionTest">
    <group id="testDefinedbutNotRaisedException">
      <test id="myFirstTestCase">
        <asserts>
          <exception id="expectedException" 
            type="java.lang.RuntimeException" action="isEqual">My Exception</exception>
        </asserts>
      </test>
    </group>
  </cluster>
</ddtunit>

=== strohitv/ddtunit-fork/src/test/resources/junitx/ddtunit/data/processing/DDT-TypeAbbreviatorTest.xml
<?xml version="1.0" ?>
<ddtunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://ddtunit.sourceforge.net/ddtunit.xsd">
    <cluster id="TypeAbbreviatorTest">
        <!--                                                                  -->
        <!-- collection type object retrieval                                 -->
        <!--                                                                  -->
        <group id="testResolve">
            <test id="abbreviatedType">
                <objs>
                    <obj id="input" type="java.lang.String">string</obj>
                </objs>
                <asserts>
                    <assert id="expected" type="java.lang.String"
                        action="isEqual">
                        java.lang.String
                    </assert>
                </asserts>
            </test>
            <test id="notAbbreviatedType">
                <objs>
                    <obj id="input" type="java.lang.String">
                        junitx.ddtunit.resources.SimpleVO
                    </obj>
                </objs>
                <asserts>
                    <assert id="expected" type="java.lang.String"
                        action="isEqual">
                        junitx.ddtunit.resources.SimpleVO
                    </assert>
                </asserts>
            </test>
        </group>
        <!--                                                                   -->
        <!--                                                                   -->
        <!--                                                                   -->
        <group id="testToString">
            <test id="dictionaryContent">
                <asserts>
                    <assert id="content" type="java.lang.Integer"
                        action="isEqual">
                        39
                    </assert>
                </asserts>
            </test>
        </group>
    </cluster>
</ddtunit>

=== strohitv/ddtunit-fork/src/test/resources/junitx/ddtunit/functest/DDT-ProcessStringDataTest.xml
<?xml version="1.0" ?>
<ddtunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="http://ddtunit.sourceforge.net/ddtunit.xsd">
  <cluster id="ProcessStringDataTest">
  <!--                                                                  -->
  <!-- java.lang.String                                                 -->
  <!--                                                                  -->
    <group id="testStringType">
      <test id="assertEmptyTagIsNotNull">
		<objs>
  		  <obj id="myString" type="string"/>
		</objs>
		<asserts>
		  <assert id="result" type="java.lang.String" action="isNotNull"/>
		</asserts>
	  </test>
      <test id="assertEmptyTagEqualsEmpty">
		<objs>
  		  <obj id="myString" type="string"/>
		</objs>
		<asserts>
		  <assert id="result" type="java.lang.String" action="isEqual">!EMPTY!</assert>
		</asserts>
	  </test>
      <test id="assertBlankTagEqualsBlank">
		<objs>
  		  <obj id="myString" type="string"><![CDATA[ ]]></obj>
		</objs>
		<asserts>
		  <assert id="result" type="java.lang.String" action="isEqual">!BLANK!</assert>
		</asserts>
	  </test>
	  <test id="assertStringIsEqual">
  		<objs>
		  <obj id="myString" type="java.lang.String">Hallo World</obj>
		</objs>
		<asserts>
		  <assert id="result" type="java.lang.String" action="isEqual">Hallo World</assert>
		</asserts>
	  </test>
	  <test id="assertStringIsEqualWithTypeShortcut">
		<objs>
		  <obj id="myString" type="string">Hallo World</obj>
		</objs>
		<asserts>
		  <assert id="result" type="java.lang.String" action="isEqual">Hallo World</assert>
		</asserts>
	  </test>
	  <test id="assertStringIsEqualIgnoreWhitespace">
		<objs>
		  <obj id="myString" type="java.lang.String">Hallo World</obj>
		</objs>
		<asserts>
		  <assert id="result" type="java.lang.String"
              action="isEqual">Hallo World</assert>
		</asserts>
	  </test>
	  <test id="assertNullStringIsNull">
		<objs>
		  <obj id="myString" type="java.lang.String">!NULL!</obj>
		</objs>
		<asserts>
		  <assert id="result" type="java.lang.String"
              action="isNull"/>
		</asserts>
	  </test>
	  <test id="differentActualAndExpectedAssertTypes">
		<objs>
		  <obj id="myString" type="java.lang.String">Hallo World</obj>
		</objs>
		<asserts>
		  <assert id="result" type="junitx.ddtunit.resources.SimpleVO"
              action="isEqual">!NULL!</assert>
		  <exception id="expected" type="junit.framework.AssertionFailedError"
              action="isSimilar">Class type differs</exception>
		</asserts>
	  </test>
	  <test id="differentCDATAStrings">
		<objs>
		  <obj id="myString" type="java.lang.String"><![CDATA[  CData type  ]]></obj>
		</objs>
 		<asserts>
		  <assert id="result" type="java.lang.String" action="isNotEqual">CData type</assert>
		</asserts>
 	  </test>
	  <test id="multilineWithEmptyInnerLineCDATAStrings">
		<objs>
		  <obj id="myString" type="java.lang.String"><![CDATA[First line

Third line]]></obj>
		</objs>
		<asserts>
		  <assert id="result" type="java.lang.String" action="isEqual">First line

Third line</assert>
		</asserts>
	  </test>
	  <test id="multilineWithEmptyOuterLineCDATAStrings">
		<objs>
		  <obj id="myString" type="java.lang.String"><![CDATA[
First line is empty, this is second
Third line

]]></obj>
		</objs>
		<asserts>
		  <assert id="result" type="java.lang.String" action="isEqual"><![CDATA[
First line is empty, this is second
Third line

]]></assert>
		</asserts>
	  </test>
	  <test id="multilineWithEmptyInnerLinesCDATAStrings">
		<objs>
		  <obj id="myString" type="java.lang.String">
First line




Sixs line
		  </obj>
		</objs>
		<asserts>
		  <assert id="result" type="java.lang.String" action="isEqual"><![CDATA[First line




Sixs line]]></assert>
		</asserts>
	  </test>
	  <test id="stringAbbreviatorOnObject">
		<objs>
		  <obj id="myString" type="string">Hallo World</obj>
		</objs>
		<asserts>
		  <assert id="result" type="java.lang.String" action="isEqual">Hallo World</assert>
		</asserts>
	  </test>
	  <test id="stringAbbreviatorOnAssert">
		<objs>
		  <obj id="myString" type="java.lang.String">Hallo World</obj>
		</objs>
		<asserts>
		  <assert id="result" type="string" action="isEqual">Hallo World</assert>
		</asserts>
	  </test>
   <test id="charType">
    <objs>
     <obj id="myString" type="java.lang.Character">c</obj>
    </objs>
    <asserts>
     <assert id="result" type="char" action="isEqual" hint="constructor">
       <item type="char">c</item>
     </assert>
    </asserts>
   </test>
  </group>
  </cluster>
</ddtunit>

=== strohitv/ddtunit-fork/src/test/resources/junitx/ddtunit/data/processing/DDT-ProcessClassGlobalObjectsTest.xml
<?xml version="1.0" ?>
<ddtunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="http://ddtunit.sourceforge.net/ddtunit.xsd">
  <resources>
      <obj id="resource" type="java.lang.String">Hallo first Resource</obj>
      <obj id="secondResource" type="java.lang.String">Hallo second Resource</obj>
  </resources>
  <cluster id="ProcessClassGlobalObjectsTest">
    <!--                                                                  -->
    <!-- read global data and assert locally                              -->
    <!--                                                                  -->
    <objs>
      <obj id="global" type="java.lang.String">Hallo first Global</obj>
      <obj id="secondGlobal" type="java.lang.String">Hallo Second Global</obj>
    </objs>
    <group id="testDirectReadOnScope">
      <test id="readDirectScopeString">
        <objs>
          <obj id="local" type="string">Hallo local World</obj>
        </objs>
        <asserts>
          <assert id="expectedLocal" type="string" action="isEqual">Hallo local World</assert>
          <assert id="expectedGlobal" type="string" action="isEqual">Hallo first Global</assert>
          <assert id="expectedResource" type="string" action="isEqual">Hallo first Resource</assert>
        </asserts>
      </test>
    </group>
    <group id="testLocalGlobalScopeAccess">
      <test id="readLocalGlobalScopeString">
        <objs>
          <obj id="local" type="string">Hallo Local</obj>
        </objs>
        <asserts>
          <assert id="expectedLocal" type="string" action="isEqual">Hallo Local</assert>
          <assert id="expectedGlobal" type="string" action="isEqual">Hallo first Global</assert>
          <assert id="expectedResource" type="string" action="isEqual">Hallo first Resource</assert>
        </asserts>
      </test>
    </group>
  </cluster>
</ddtunit>
