=== strohitv/ddtunit-fork/src/main/resources/junitx/ddtunit/data/processing/parser/ddtunit.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 elementFormDefault="qualified" attributeFormDefault="unqualified">
 <xsd:element name="ddtunit">
  <xsd:annotation>
   <xsd:documentation>Schema for DDTUnit test data</xsd:documentation>
  </xsd:annotation>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element name="resources" type="objSetType" minOccurs="0" maxOccurs="1" />
    <xsd:sequence minOccurs="1" maxOccurs="unbounded">
     <xsd:element ref="cluster" />
    </xsd:sequence>
   </xsd:sequence>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name="cluster">
  <xsd:complexType>
   <xsd:annotation>
    <xsd:documentation>
     cluster contains multiple groups of tests
    </xsd:documentation>
   </xsd:annotation>
   <xsd:sequence>
    <xsd:element ref="description" minOccurs="0" maxOccurs="1" />
    <xsd:element name="objs" type="objSetType" minOccurs="0" maxOccurs="1" />
    <xsd:sequence minOccurs="0" maxOccurs="unbounded">
     <xsd:element name="group">
      <xsd:complexType>
       <xsd:complexContent>
        <xsd:extension base="groupType">
         <xsd:attribute name="id" type="xsd:string" use="required" />
        </xsd:extension>
       </xsd:complexContent>
      </xsd:complexType>
     </xsd:element>
    </xsd:sequence>
   </xsd:sequence>
   <xsd:attribute name="id" type="xsd:string" use="required" />
  </xsd:complexType>
 </xsd:element>

 <xsd:complexType name="groupType">
  <xsd:annotation>
   <xsd:documentation>
    group containing multiple test definitions
   </xsd:documentation>
  </xsd:annotation>
  <xsd:sequence minOccurs="0" maxOccurs="unbounded">
   <xsd:element ref="test" />
  </xsd:sequence>
 </xsd:complexType>

 <xsd:element name="test">
  <xsd:annotation>
   <xsd:documentation>
    Definition of object element used for mapping to objects of test framework
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexType>
   <xsd:annotation>
    <xsd:documentation>
     test contains set of objects and/or set of asserts
    </xsd:documentation>
   </xsd:annotation>
   <xsd:sequence>
    <xsd:element name="objs" type="objSetType" minOccurs="0" />
    <xsd:element name="asserts" type="assertSetType" minOccurs="0" />
   </xsd:sequence>
   <xsd:attribute name="id" type="xsd:string" use="required" />
  </xsd:complexType>
 </xsd:element>

 <xsd:complexType name="objSetType">
  <xsd:annotation>
   <xsd:documentation>
    Definition of set of object elements used for mapping to Java Object
    instance
   </xsd:documentation>
  </xsd:annotation>
  <xsd:sequence minOccurs="0" maxOccurs="unbounded">
   <xsd:element ref="obj" />
  </xsd:sequence>
 </xsd:complexType>

 <xsd:complexType name="assertSetType">
  <xsd:annotation>
   <xsd:documentation>
    Definition of assert element used for Java objects containing all
    information about asserts to process
   </xsd:documentation>
  </xsd:annotation>
  <xsd:sequence minOccurs="0" maxOccurs="unbounded">
   <xsd:sequence>
    <xsd:element ref="assert" minOccurs="0" />
    <xsd:element ref="exception" minOccurs="0" />
   </xsd:sequence>
  </xsd:sequence>
 </xsd:complexType>

 <xsd:simpleType name="objectAssertType">
  <xsd:restriction base="xsd:string">
   <xsd:enumeration value="isTrue" />
   <xsd:enumeration value="isFalse" />
   <xsd:enumeration value="isEqual" />
   <xsd:enumeration value="isNotEqual" />
   <xsd:enumeration value="isSame" />
   <xsd:enumeration value="isNotSame" />
   <xsd:enumeration value="isNull" />
   <xsd:enumeration value="isNotNull" />
   <xsd:enumeration value="isGT" />
   <xsd:enumeration value="isNotGT" />
   <xsd:enumeration value="isLT" />
   <xsd:enumeration value="isNotLT" />
   <xsd:enumeration value="isInRange" />
   <xsd:enumeration value="isNotInRange" />
   <xsd:enumeration value="isContainedIn" />
   <xsd:enumeration value="isNotContainedIn" />
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:simpleType name="exceptionAssertType">
  <xsd:restriction base="xsd:string">
   <xsd:enumeration value="isEqual" />
   <xsd:enumeration value="isSimilar" />
   <xsd:enumeration value="isInstanceOf" />
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:simpleType name="hintType">
  <xsd:restriction base="xsd:string">
   <xsd:enumeration value="fields" />
   <xsd:enumeration value="collection" />
   <xsd:enumeration value="map" />
   <xsd:enumeration value="constant" />
   <xsd:enumeration value="constructor" />
   <xsd:enumeration value="call" />
   <xsd:enumeration value="date" />
   <xsd:enumeration value="bean" />
   <xsd:enumeration value="array" />
  </xsd:restriction>
 </xsd:simpleType>


 <xsd:complexType name="anyType">
  <xsd:sequence minOccurs="0" maxOccurs="unbounded">
   <xsd:any namespace="##any" processContents="skip" />
  </xsd:sequence>
 </xsd:complexType>

 <xsd:element name="description" type="xsd:string" />

 <xsd:element name="obj">
  <xsd:annotation>
   <xsd:documentation>
    Definition of object element used for mapping to objects of test framework
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexType mixed="true">
   <xsd:sequence minOccurs="0" maxOccurs="unbounded">
    <xsd:any namespace="##any" processContents="skip" />
   </xsd:sequence>
   <xsd:attributeGroup ref="objAttributes" />
  </xsd:complexType>
 </xsd:element>

 <xsd:attributeGroup name="objAttributes">
  <xsd:attribute name="id" type="xsd:string" use="required" />
  <xsd:attribute name="type" type="xsd:string" use="required" />
  <xsd:attribute name="hint" type="hintType" use="optional" default="fields" />
  <xsd:attribute name="keytype" type="xsd:string" use="optional"
   default="string" />
  <xsd:attribute name="valuetype" type="xsd:string" use="optional"
   default="string" />
  <xsd:attribute name="method" type="xsd:string" use="optional"
   default="constructor" />
  <xsd:attribute name="refid" type="xsd:string" use="optional" />
  <xsd:attribute name="calltype" type="xsd:string" use="optional" />
  <xsd:attribute name="dateformat" type="xsd:string" />
  <xsd:attribute name="locale" type="xsd:string" />
    </xsd:attributeGroup>

 <xsd:element name="assert">
  <xsd:annotation>
   <xsd:documentation>
    Definition of assert/exception element used for mapping to assert objects of
    test framework
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexType mixed="true">
   <xsd:sequence minOccurs="0" maxOccurs="unbounded">
    <xsd:any namespace="##any" processContents="skip" />
   </xsd:sequence>
   <xsd:attributeGroup ref="assertAttributes" />
  </xsd:complexType>
 </xsd:element>

 <xsd:attributeGroup name="assertAttributes">
  <xsd:attributeGroup ref="objAttributes" />
  <xsd:attribute name="action" type="objectAssertType" use="required" />
 </xsd:attributeGroup>

 <xsd:element name="exception">
  <xsd:annotation>
   <xsd:documentation>
    Definition of exception element used for mapping to assert objects on
    expected exceptions of test framework
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexType mixed="true">
   <xsd:sequence minOccurs="0" maxOccurs="unbounded">
    <xsd:any namespace="##any" processContents="skip" />
   </xsd:sequence>
   <xsd:attributeGroup ref="exceptionAttributes" />
  </xsd:complexType>
 </xsd:element>

 <xsd:attributeGroup name="exceptionAttributes">
  <xsd:attributeGroup ref="objAttributes" />
  <xsd:attribute name="action" type="exceptionAssertType" use="required" />
 </xsd:attributeGroup>

</xsd:schema>

=== strohitv/ddtunit-fork/src/test/resources/junitx/ddtunit/functest/DDT-ProcessDateDataTest.xml
<?xml version="1.0" ?>
<ddtunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://ddtunit.sourceforge.net/ddtunit.xsd">
 <cluster id="ProcessDateDataTest">
  <!--                                                                  -->
  <!-- java.util.Date                                                   -->
  <!--                                                                  -->
  <group id="testDateType">
   <test id="readSimpleDateNull">
    <objs>
     <obj id="myDate" hint="date" type="java.util.Date">!NULL!</obj>
    </objs>
    <asserts>
     <assert id="result" type="java.util.Date" action="isNull" />
    </asserts>
   </test>
   <test id="readSimpleDateNotNull">
    <objs>
     <obj id="myDate" hint="date" type="java.util.Date">
      01.05.2005 00:00:00.000
     </obj>
    </objs>
    <asserts>
     <assert id="result" type="java.util.Date" action="isNotNull" />
    </asserts>
   </test>
   <test id="longEqualsMedium">
    <objs>
     <obj id="myDate" hint="date" type="date">
      01.05.2005 00:00:00.000
     </obj>
    </objs>
    <asserts>
     <assert id="result" hint="date" type="java.util.Date" action="isEqual">
      01.05.2005 00:00:00
     </assert>
    </asserts>
   </test>
   <test id="longEqualsShort">
    <objs>
     <obj id="myDate" hint="date" type="java.util.Date">
      01.05.2005 00:00:00.000
     </obj>
    </objs>
    <asserts>
     <assert id="result" hint="date" type="java.util.Date" action="isEqual">
      01.05.2005
     </assert>
    </asserts>
   </test>
   <test id="longEqualsShortcutType">
    <objs>
     <obj id="myDate" hint="date" type="java.util.Date">
      01.05.2005 00:00:00.000
     </obj>
    </objs>
    <asserts>
     <assert id="result" hint="date" type="udate" action="isEqual">
      01.05.2005
     </assert>
    </asserts>
   </test>
   <test id="sysdateGTThanOldDate">
    <objs>
     <obj id="myDate" hint="date" type="java.util.Date">!SYSDATE!</obj>
    </objs>
    <asserts>
     <assert id="result" hint="date" type="udate" action="isGT">
      01.05.2005
     </assert>
    </asserts>
   </test>
   <test id="sysdateGTThanOldDateWithException">
    <objs>
     <obj id="myDate" hint="date" type="java.util.Date">!SYSDATE!</obj>
    </objs>
    <asserts>
     <assert id="result" hint="date" type="udate" action="isNotGT">
      01.05.2005
     </assert>
     <exception id="expected" type="junit.framework.AssertionFailedError"
      action="isSimilar" hint="constructor">
      <item type="string">Expected action:</item>
     </exception>
    </asserts>
   </test>
   <test id="systimeGTThanOldDate">
    <objs>
     <obj id="myDate" hint="date" type="java.util.Date">!SYSTIME!</obj>
    </objs>
    <asserts>
     <assert id="result" hint="date" type="udate" action="isGT">
      01.06.2005
     </assert>
    </asserts>
   </test>
   <test id="systimeGTThanOldDateWithException">
    <objs>
     <obj id="myDate" hint="date" type="java.util.Date">!SYSTIME!</obj>
    </objs>
    <asserts>
     <assert id="result" hint="date" type="udate" action="isNotGT">
      01.05.2005
     </assert>
     <exception id="expected" type="junit.framework.AssertionFailedError"
      action="isSimilar" hint="constructor">
      <item type="string">Expected action:</item>
     </exception>
    </asserts>
   </test>
  </group>
  <group id="testSpecificDateType">
   <test id="readShortDate">
    <objs>
     <obj id="myDate" hint="date" type="date" dateformat="short">06.12.2007</obj>
    </objs>
    <asserts>
     <assert id="result" hint="date" type="java.util.Date" action="isEqual">06.12.2007 00:00:00</assert>
    </asserts>
   </test>
   <test id="readMediumDate">
    <objs>
     <obj id="myDate" hint="date" type="date" dateformat="medium">06.12.2007 10:11:12</obj>
    </objs>
    <asserts>
     <assert id="result" hint="date" type="java.util.Date" action="isEqual">06.12.2007 10:11:12</assert>
    </asserts>
   </test>
   <test id="readLongDate">
    <objs>
     <obj id="myDate" hint="date" type="date" dateformat="long">06.12.2007 10:11:12.123</obj>
    </objs>
    <asserts>
     <assert id="result" hint="date" type="date" action="isEqual">06.12.2007 10:11:12.123</assert>
    </asserts>
   </test>
   <test id="readExampleDate">
    <objs>
     <obj id="myDate" hint="date" type="date" dateformat="example">Thu Dec 06 10:11:12 CET 2007</obj>
    </objs>
    <asserts>
     <assert id="result" hint="date" type="date" action="isEqual">06.12.2007 10:11:12</assert>
    </asserts>
   </test>
   <test id="readExampleDateUnnamed">
    <objs>
     <obj id="myDate" hint="date" type="date">Thu Dec 06 10:11:12 CET 2007</obj>
    </objs>
    <asserts>
     <assert id="result" hint="date" type="date" action="isEqual">06.12.2007 10:11:12</assert>
    </asserts>
   </test>
   <test id="readFreeDate">
    <objs>
     <obj id="myDate" hint="date" type="date" dateformat="EEE MMM dd HH:mm:ss zzz yyyy">Thu Dec 06 10:11:12 CET 2007</obj>
    </objs>
    <asserts>
     <assert id="result" hint="date" type="date" action="isEqual">06.12.2007 10:11:12</assert>
    </asserts>
   </test>
   <test id="readFreeDateWithLocale">
    <objs>
     <obj id="myDate" hint="date" type="date" dateformat="EE MMM dd HH:mm:ss zzz yyyy" locale="de_DE">Di Dez 06 10:11:12 MET 2007</obj>
    </objs> 
    <asserts>
     <assert id="result" hint="date" type="date" action="isEqual">06.12.2007 10:11:12</assert>
    </asserts>
   </test>
   </group>
 </cluster>
</ddtunit>
