=== strohitv/ddtunit-fork/src/main/resources/junitx/ddtunit/data/processing/parser/ddtunit.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 elementFormDefault="qualified" attributeFormDefault="unqualified">
 <xsd:element name="ddtunit">
  <xsd:annotation>
   <xsd:documentation>Schema for DDTUnit test data</xsd:documentation>
  </xsd:annotation>
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element name="resources" type="objSetType" minOccurs="0" maxOccurs="1" />
    <xsd:sequence minOccurs="1" maxOccurs="unbounded">
     <xsd:element ref="cluster" />
    </xsd:sequence>
   </xsd:sequence>
  </xsd:complexType>
 </xsd:element>

 <xsd:element name="cluster">
  <xsd:complexType>
   <xsd:annotation>
    <xsd:documentation>
     cluster contains multiple groups of tests
    </xsd:documentation>
   </xsd:annotation>
   <xsd:sequence>
    <xsd:element ref="description" minOccurs="0" maxOccurs="1" />
    <xsd:element name="objs" type="objSetType" minOccurs="0" maxOccurs="1" />
    <xsd:sequence minOccurs="0" maxOccurs="unbounded">
     <xsd:element name="group">
      <xsd:complexType>
       <xsd:complexContent>
        <xsd:extension base="groupType">
         <xsd:attribute name="id" type="xsd:string" use="required" />
        </xsd:extension>
       </xsd:complexContent>
      </xsd:complexType>
     </xsd:element>
    </xsd:sequence>
   </xsd:sequence>
   <xsd:attribute name="id" type="xsd:string" use="required" />
  </xsd:complexType>
 </xsd:element>

 <xsd:complexType name="groupType">
  <xsd:annotation>
   <xsd:documentation>
    group containing multiple test definitions
   </xsd:documentation>
  </xsd:annotation>
  <xsd:sequence minOccurs="0" maxOccurs="unbounded">
   <xsd:element ref="test" />
  </xsd:sequence>
 </xsd:complexType>

 <xsd:element name="test">
  <xsd:annotation>
   <xsd:documentation>
    Definition of object element used for mapping to objects of test framework
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexType>
   <xsd:annotation>
    <xsd:documentation>
     test contains set of objects and/or set of asserts
    </xsd:documentation>
   </xsd:annotation>
   <xsd:sequence>
    <xsd:element name="objs" type="objSetType" minOccurs="0" />
    <xsd:element name="asserts" type="assertSetType" minOccurs="0" />
   </xsd:sequence>
   <xsd:attribute name="id" type="xsd:string" use="required" />
  </xsd:complexType>
 </xsd:element>

 <xsd:complexType name="objSetType">
  <xsd:annotation>
   <xsd:documentation>
    Definition of set of object elements used for mapping to Java Object
    instance
   </xsd:documentation>
  </xsd:annotation>
  <xsd:sequence minOccurs="0" maxOccurs="unbounded">
   <xsd:element ref="obj" />
  </xsd:sequence>
 </xsd:complexType>

 <xsd:complexType name="assertSetType">
  <xsd:annotation>
   <xsd:documentation>
    Definition of assert element used for Java objects containing all
    information about asserts to process
   </xsd:documentation>
  </xsd:annotation>
  <xsd:sequence minOccurs="0" maxOccurs="unbounded">
   <xsd:sequence>
    <xsd:element ref="assert" minOccurs="0" />
    <xsd:element ref="exception" minOccurs="0" />
   </xsd:sequence>
  </xsd:sequence>
 </xsd:complexType>

 <xsd:simpleType name="objectAssertType">
  <xsd:restriction base="xsd:string">
   <xsd:enumeration value="isTrue" />
   <xsd:enumeration value="isFalse" />
   <xsd:enumeration value="isEqual" />
   <xsd:enumeration value="isNotEqual" />
   <xsd:enumeration value="isSame" />
   <xsd:enumeration value="isNotSame" />
   <xsd:enumeration value="isNull" />
   <xsd:enumeration value="isNotNull" />
   <xsd:enumeration value="isGT" />
   <xsd:enumeration value="isNotGT" />
   <xsd:enumeration value="isLT" />
   <xsd:enumeration value="isNotLT" />
   <xsd:enumeration value="isInRange" />
   <xsd:enumeration value="isNotInRange" />
   <xsd:enumeration value="isContainedIn" />
   <xsd:enumeration value="isNotContainedIn" />
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:simpleType name="exceptionAssertType">
  <xsd:restriction base="xsd:string">
   <xsd:enumeration value="isEqual" />
   <xsd:enumeration value="isSimilar" />
   <xsd:enumeration value="isInstanceOf" />
  </xsd:restriction>
 </xsd:simpleType>

 <xsd:simpleType name="hintType">
  <xsd:restriction base="xsd:string">
   <xsd:enumeration value="fields" />
   <xsd:enumeration value="collection" />
   <xsd:enumeration value="map" />
   <xsd:enumeration value="constant" />
   <xsd:enumeration value="constructor" />
   <xsd:enumeration value="call" />
   <xsd:enumeration value="date" />
   <xsd:enumeration value="bean" />
   <xsd:enumeration value="array" />
  </xsd:restriction>
 </xsd:simpleType>


 <xsd:complexType name="anyType">
  <xsd:sequence minOccurs="0" maxOccurs="unbounded">
   <xsd:any namespace="##any" processContents="skip" />
  </xsd:sequence>
 </xsd:complexType>

 <xsd:element name="description" type="xsd:string" />

 <xsd:element name="obj">
  <xsd:annotation>
   <xsd:documentation>
    Definition of object element used for mapping to objects of test framework
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexType mixed="true">
   <xsd:sequence minOccurs="0" maxOccurs="unbounded">
    <xsd:any namespace="##any" processContents="skip" />
   </xsd:sequence>
   <xsd:attributeGroup ref="objAttributes" />
  </xsd:complexType>
 </xsd:element>

 <xsd:attributeGroup name="objAttributes">
  <xsd:attribute name="id" type="xsd:string" use="required" />
  <xsd:attribute name="type" type="xsd:string" use="required" />
  <xsd:attribute name="hint" type="hintType" use="optional" default="fields" />
  <xsd:attribute name="keytype" type="xsd:string" use="optional"
   default="string" />
  <xsd:attribute name="valuetype" type="xsd:string" use="optional"
   default="string" />
  <xsd:attribute name="method" type="xsd:string" use="optional"
   default="constructor" />
  <xsd:attribute name="refid" type="xsd:string" use="optional" />
  <xsd:attribute name="calltype" type="xsd:string" use="optional" />
  <xsd:attribute name="dateformat" type="xsd:string" />
  <xsd:attribute name="locale" type="xsd:string" />
    </xsd:attributeGroup>

 <xsd:element name="assert">
  <xsd:annotation>
   <xsd:documentation>
    Definition of assert/exception element used for mapping to assert objects of
    test framework
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexType mixed="true">
   <xsd:sequence minOccurs="0" maxOccurs="unbounded">
    <xsd:any namespace="##any" processContents="skip" />
   </xsd:sequence>
   <xsd:attributeGroup ref="assertAttributes" />
  </xsd:complexType>
 </xsd:element>

 <xsd:attributeGroup name="assertAttributes">
  <xsd:attributeGroup ref="objAttributes" />
  <xsd:attribute name="action" type="objectAssertType" use="required" />
 </xsd:attributeGroup>

 <xsd:element name="exception">
  <xsd:annotation>
   <xsd:documentation>
    Definition of exception element used for mapping to assert objects on
    expected exceptions of test framework
   </xsd:documentation>
  </xsd:annotation>
  <xsd:complexType mixed="true">
   <xsd:sequence minOccurs="0" maxOccurs="unbounded">
    <xsd:any namespace="##any" processContents="skip" />
   </xsd:sequence>
   <xsd:attributeGroup ref="exceptionAttributes" />
  </xsd:complexType>
 </xsd:element>

 <xsd:attributeGroup name="exceptionAttributes">
  <xsd:attributeGroup ref="objAttributes" />
  <xsd:attribute name="action" type="exceptionAssertType" use="required" />
 </xsd:attributeGroup>

</xsd:schema>

=== strohitv/ddtunit-fork/src/test/resources/junitx/ddtunit/data/DDT-VerifyTestOrderExecutionTest.xml
<?xml version="1.0" ?>
<ddtunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="http://ddtunit.sourceforge.net/ddtunit.xsd">
  <cluster id="VerifyTestOrderExecutionTest">
    <objs>
    <obj type="string" id="order">010203040506070809101112131415</obj>
    </objs>
  <!--                                                                  -->
  <!-- java.lang.String                                                 -->
  <!--                                                                  -->
    <group id="testMethodTestOrder">
      <test id="01">
		<objs>
  		  <obj id="myString" type="string"/>
		</objs>
		<asserts>
		  <assert id="result" type="java.lang.String" action="isNotNull"/>
		</asserts>
	  </test>
      <test id="02">
		<objs>
  		  <obj id="myString" type="string"/>
		</objs>
		<asserts>
		  <assert id="result" type="java.lang.String" action="isEqual">!EMPTY!</assert>
		</asserts>
	  </test>
	  <test id="03">
  		<objs>
		  <obj id="myString" type="java.lang.String">Hallo World</obj>
		</objs>
		<asserts>
		  <assert id="result" type="java.lang.String" action="isEqual">Hallo World</assert>
		</asserts>
	  </test>
	  <test id="04">
  		<objs>
		  <obj id="myString" type="java.lang.String">Hallo World</obj>
		</objs>
		<asserts>
		  <assert id="result" type="java.lang.String" action="isEqual">Hallo World</assert>
		</asserts>
	  </test>
	  <test id="05">
		<objs>
		  <obj id="myString" type="string">Hallo World</obj>
		</objs>
		<asserts>
		  <assert id="result" type="java.lang.String" action="isEqual">Hallo World</assert>
		</asserts>
	  </test>
	  <test id="06">
		<objs>
		  <obj id="myString" type="java.lang.String">Hallo World</obj>
		</objs>
		<asserts>
		  <assert id="result" type="java.lang.String"
              action="isEqual">Hallo World</assert>
		</asserts>
	  </test>
	  <test id="07">
		<objs>
		  <obj id="myString" type="java.lang.String">!NULL!</obj>
		</objs>
		<asserts>
		  <assert id="result" type="java.lang.String"
              action="isNull"/>
		</asserts>
	  </test>
	  <test id="08">
		<objs>
		  <obj id="myString" type="java.lang.String">Hallo World</obj>
		</objs>
		<asserts>
		  <assert id="result" type="junitx.ddtunit.resources.SimpleVO"
              action="isEqual">!NULL!</assert>
		  <exception id="expected" type="junit.framework.AssertionFailedError"
              action="isSimilar">Class type differs</exception>
		</asserts>
	  </test>
	  <test id="09">
		<objs>
		  <obj id="myString" type="java.lang.String"><![CDATA[CData type]]></obj>
		</objs>
 		<asserts>
		  <assert id="result" type="java.lang.String" action="isEqual">CData type</assert>
		</asserts>
 	  </test>
	  <test id="10">
		<objs>
		  <obj id="myString" type="java.lang.String"><![CDATA[First line

Second line]]></obj>
		</objs>
		<asserts>
		  <assert id="result" type="java.lang.String" action="isEqual">First line

Second line</assert>
		</asserts>
	  </test>
	  <test id="11">
		<objs>
		  <obj id="myString" type="java.lang.String"><![CDATA[
First line is empty, this is second
Third line

]]></obj>
		</objs>
		<asserts>
		  <assert id="result" type="java.lang.String" action="isEqual"><![CDATA[
First line is empty, this is second
Third line

]]></assert>
		</asserts>
	  </test>
	  <test id="12">
		<objs>
		  <obj id="myString" type="java.lang.String">
First line




Sixs line
		  </obj>
		</objs>
		<asserts>
		  <assert id="result" type="java.lang.String" action="isEqual"><![CDATA[First line




Sixs line]]></assert>
		</asserts>
	  </test>
	  <test id="13">
		<objs>
		  <obj id="myString" type="string">Hallo World</obj>
		</objs>
		<asserts>
		  <assert id="result" type="java.lang.String" action="isEqual">Hallo World</assert>
		</asserts>
	  </test>
	  <test id="14">
		<objs>
		  <obj id="myString" type="java.lang.String">Hallo World</obj>
		</objs>
		<asserts>
		  <assert id="result" type="string" action="isEqual">Hallo World</assert>
		</asserts>
	  </test>
   <test id="15">
    <objs>
     <obj id="myString" type="java.lang.Character">c</obj>
    </objs>
    <asserts>
     <assert id="result" type="char" action="isEqual" hint="constructor">
       <item type="char">c</item>
     </assert>
    </asserts>
   </test>
  </group>
  </cluster>
</ddtunit>

=== strohitv/ddtunit-fork/src/test/resources/junitx/ddtunit/data/DDT-DefectXMLTest.xml
<?xml version="1.0" ?>
<ddtunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="http://ddtunit.sourceforge.net/ddtunit.xsd">
  <cluster id="SimpleDDTUnitTest">
    <!--                                                                  -->
    <!-- simple object retrieval                                          -->
    <!--                                                                  -->
    <group id="testRetrieveObjectData">
      <test id="myFirstTestCase">
        <objs>
          <obj id="myObj" type="java.lang.String">My first String</obj>
        </objs>
      </test>
      <test id="mySecondTestCase">
        <objs>
          <obj id="myObj" type="java.lang.String" wrong="extra.attribute">
             My second String</obj>
        </objs>
      </test>
    </group>
  </cluster>
</ddtunit>

=== strohitv/ddtunit-fork/src/test/resources/junitx/ddtunit/DDT-XmlEntityResourceTest.xml
<?xml version="1.0" ?>
<!DOCTYPE ddtunit [
  <!ENTITY sameResource SYSTEM "DDT-XmlEntityResourceSameDirTest.xml">
]>
<ddtunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="http://ddtunit.sourceforge.net/ddtunit.xsd">
  <cluster id="XmlEntityResourceTest">
    <objs>
      &sameResource;
    </objs>
    <!--                                                                  -->
    <!-- simple object retrieval                                          -->
    <!--                                                                  -->
    <group id="testReadExternalEntityParam">
      <test id="myFirstTestCase">
        <objs>
          <obj id="myparam" refid="resourceTest1Type1" type="string" />
        </objs>
        <asserts>
          <assert id="result" type="string" action="isEqual">Value A</assert>
        </asserts>
      </test>
      <test id="mySecondTestCase">
        <objs>
          <obj id="myparam" refid="resourceTest2Type1" type="string" />
        </objs>
        <asserts>
          <assert id="result" type="string" action="isEqual">Value B</assert>
        </asserts>
      </test>
    </group>
  </cluster>
</ddtunit>

=== strohitv/ddtunit-fork/src/test/resources/junitx/ddtunit/DDT-DDTRunMonitorTest.xml
<?xml version="1.0" ?>
<ddtunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="http://ddtunit.sourceforge.net/ddtunit.xsd">
  <cluster id="DDTRunMonitorTest">
    <!--                                                                  -->
    <!-- simple object retrieval                                          -->
    <!--                                                                  -->
    <group id="testZCorrectMethod">
      <test id="myFirstTestCase">
        <objs>
          <obj id="myObj" type="string">My first String</obj>
        </objs>
        <asserts>
          <assert id="result" type="string" action="isEqual">My first String</assert>
        </asserts>
      </test>
      <test id="mySecondTestCase">
        <objs>
          <obj id="myObj" type="string">My second Strin</obj>
        </objs>
        <asserts>
          <assert id="result" type="string" action="isEqual">My first String</assert>
        </asserts>
      </test>
    </group>
    <!--                                                                  -->
    <!-- simple assert processing                                         -->
    <!--                                                                  -->
    <group id="testWrongMethod">
      <test id="myFirstTestCase">
        <objs>
          <obj id="myObj" type="java.lang.String">My first String</obj>
        </objs>
        <asserts>
          <assert id="result" type="java.lang.String" action="isEqual">My first String</assert>
        </asserts>
      </test>
      <test id="mySecondTestCase">
        <objs>
          <obj id="myObj" type="java.lang.String">My second String</obj>
        </objs>
        <asserts>
          <exception id="expected" type="junit.framework.AssertionFailedError" action="isSimilar">
            Should allways fail</exception>
        </asserts>
      </test>
      <test id="myThirdTestCase">
        <objs>
          <obj id="myObj" type="java.lang.String">My first String</obj>
        </objs>
        <asserts>
          <assert id="result" type="java.lang.String" action="isEqual">My first String</assert>
        </asserts>
      </test>
    </group>
  </cluster>
</ddtunit>

=== strohitv/ddtunit-fork/src/test/resources/junitx/ddtunit/DDT-SpecificationAssertTest.xml
<?xml version="1.0" ?>
<ddtunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://ddtunit.sourceforge.net/ddtunit.xsd">
 <cluster id="SpecificationAssertTest">
  <!--                                                                  -->
  <!-- simple object retrieval                                          -->
  <!--                                                                  -->
  <group id="testMethod">
    <test id="myFirstTestCase">
	 	<objs>
		  <obj id="myObj" type="java.lang.String">Hallo World</obj>
		</objs>
		<asserts>
      <exception id="expected" type="junit.framework.AssertionFailedError" action="isSimilar">
        <![CDATA[Assert(result2):Object should be null on assert (result2)]]>
      </exception>
		  <assert id="result" type="java.lang.String" action="isEqual">Hallo Country</assert>
      <assert id="result2" type="java.lang.String" action="isNull" />
      <assert id="result3" type="java.lang.String" action="isEqual">Hallo World</assert>
		</asserts>
	  </test>
    <test id="mySecondTestCase">
   <objs>
    <obj id="myObj" type="java.lang.String">Hallo Germany</obj>
  </objs>
  <asserts>
    <exception id="expected" type="junit.framework.AssertionFailedError" action="isSimilar">
      <![CDATA[Assert(result2):Wrong isSame assert (result2) expected same:<First line> was not:<Hallo Germany>]]>
    </exception>
    <assert id="result" type="java.lang.String" action="isEqual">Hallo America</assert>
    <assert id="result2" type="java.lang.String" action="isSame">First line</assert>
    <assert id="result3" type="java.lang.String" action="isEqual">Goodbye</assert>
  </asserts>
   </test>
    <test id="myThirdTestCase">
   <objs>
    <obj id="myObj" type="java.lang.String">Goodbye, Hallo</obj>
  </objs>
  <asserts>
    <exception id="expected" type="junit.framework.AssertionFailedError" action="isSimilar">
      <![CDATA[Assert(result):Wrong isEqual assert on (multiline) string [position 0] expected:<Hallo> but was:<Goodbye, Hallo>]]>
    </exception>
    <assert id="result" type="java.lang.String" action="isEqual">Hallo</assert>
    <assert id="result2" type="java.lang.String" action="isEqual">Goodbye</assert>
    <assert id="result3" type="java.lang.String" action="isEqual">Tschuess</assert>
  </asserts>
   </test>
  </group>
 </cluster>
</ddtunit>

=== strohitv/ddtunit-fork/src/test/resources/junitx/ddtunit/data/DDT-ObjectAsserterTest.xml
<?xml version="1.0" ?>
<ddtunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://ddtunit.sourceforge.net/ddtunit.xsd">
	<cluster id="ObjectAsserterTest">
		<!--                                                                  -->
		<!-- Check validity of isContained in action                          -->
		<!--                                                                  -->
		<group id="testIsContainedIn">
			<test id="BooleanCollectionCheck">
				<objs>
					<obj id="actualObj" type="boolean">true</obj>
					<obj id="actionId" type="string">result</obj>
					<obj id="expectedType" type="string">java.util.Vector</obj>
					<obj id="actionType" type="string">isContainedIn</obj>
					<obj id="expectedObj" type="java.util.Vector"
						hint="collection" valuetype="boolean">
						<item>true</item>
						<item>false</item>
					</obj>
				</objs>
			</test>
			<test id="BooleanCollectionCheck2">
				<objs>
					<obj id="actualObj" type="boolean">true</obj>
					<obj id="actionId" type="string">result</obj>
					<obj id="expectedType" type="string">java.util.Vector</obj>
					<obj id="actionType" type="string">isNotContainedIn</obj>
					<obj id="expectedObj" type="java.util.Vector"
						hint="collection" valuetype="boolean">
						<item>false</item>
					</obj>
				</objs>
			</test>
			<test id="BooleanCollectionCheckAssertError">
				<objs>
					<obj id="actualObj" type="boolean">true</obj>
					<obj id="actionId" type="string">result</obj>
					<obj id="expectedType" type="string">java.util.Vector</obj>
					<obj id="actionType" type="string">isContainedIn</obj>
					<obj id="expectedObj" type="java.util.Vector"
						hint="collection" valuetype="boolean">
						<item>false</item>
					</obj>
				</objs>
				<asserts>
					<exception id="expected"
						type="junit.framework.AssertionFailedError" action="isInstanceOf" />
				</asserts>
			</test>
		</group>
		<group id="testIsInRange">
			<test id="LongValidRangeCheck">
				<objs>
					<obj id="actualObj" type="long">5</obj>
					<obj id="actionId" type="string">result</obj>
					<obj id="expectedType" type="string">
						junitx.ddtunit.data.ComparableRange
					</obj>
					<obj id="actionType" type="string">isInRange</obj>
					<obj id="expectedObj" type="range">
						<start type="long">0</start>
						<end type="long">10</end>
					</obj>
				</objs>
			</test>
			<test id="LongInvalidRangeCheck">
				<objs>
					<obj id="actualObj" type="long">11</obj>
					<obj id="actionId" type="string">result</obj>
					<obj id="expectedType" type="string">
						junitx.ddtunit.data.ComparableRange
					</obj>
					<obj id="actionType" type="string">isInRange</obj>
					<obj id="expectedObj" type="range">
						<start type="long">0</start>
						<end type="long">10</end>
					</obj>
				</objs>
				<asserts>
				  <exception id="expected" type="junit.framework.AssertionFailedError"
				    action="isInstanceOf" />
				</asserts>
			</test>
			<test id="LongValidOutOfRangeCheck">
				<objs>
					<obj id="actualObj" type="long">11</obj>
					<obj id="actionId" type="string">result</obj>
					<obj id="expectedType" type="string">
						junitx.ddtunit.data.ComparableRange
					</obj>
					<obj id="actionType" type="string">isNotInRange</obj>
					<obj id="expectedObj" type="range">
						<start type="long">0</start>
						<end type="long">10</end>
					</obj>
				</objs>
			</test>
		</group>
	</cluster>
</ddtunit>

=== strohitv/ddtunit-fork/src/test/resources/junitx/ddtunit/functest/DDT-ProcessConstantValuesTest.xml
<?xml version="1.0" ?>
<ddtunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://ddtunit.sourceforge.net/ddtunit.xsd">
	<cluster id="ProcessConstantValuesTest">
		<!--                                                                  -->
		<!-- instanciate object that is public final field of a class         -->
		<!-- with only private constructor                                    -->
		<!--                                                                  -->
		<group id="testConstantsAsObjectsAndFields">
			<test id="useTypesafeEnumAsObject">
				<objs>
					<obj id="myValue"
						type="junitx.ddtunit.resources.SimpleTypeSafeEnum"
						hint="constant">
						FIRST_ENUM
					</obj>
				</objs>
				<asserts>
					<assert id="type" type="string" action="isEqual">
						junitx.ddtunit.resources.SimpleTypeSafeEnum
					</assert>
					<assert id="result"
						type="junitx.ddtunit.resources.SimpleTypeSafeEnum" hint="constant"
						action="isEqual">
						FIRST_ENUM
					</assert>
				</asserts>
			</test>
			<test id="useConstantAsObject">
				<objs>
					<obj id="myValue"
						type="junitx.ddtunit.resources.SimpleConstants" hint="constant">
						MY_STRING_CONSTANT
					</obj>
				</objs>
				<asserts>
					<assert id="result" type="string"
						action="isEqual">
						Hallo World
					</assert>
					<assert id="type" type="string" action="isEqual">
						java.lang.String
					</assert>
				</asserts>
			</test>
			<test id="useConstantAsField">
				<objs>
					<obj id="myValue"
						type="junitx.ddtunit.resources.SimpleVO">
						<stringValue
							type="junitx.ddtunit.resources.SimpleConstants"
							hint="constant">
							MY_STRING_CONSTANT
						</stringValue>
					</obj>
				</objs>
				<asserts>
					<assert id="result"
						type="junitx.ddtunit.resources.SimpleVO" action="isEqual">
						<stringValue>Hallo World</stringValue>
					</assert>
					<assert id="type" type="string" action="isEqual">
						junitx.ddtunit.resources.SimpleVO
					</assert>
				</asserts>
			</test>
		</group>
		<group id="testConstantsAsContainerEntries">
			<test id="useConstantAsCollectionEntry">
				<objs>
					<obj id="myValue" type="vector" hint="collection">
						<item
							type="junitx.ddtunit.resources.SimpleConstants"
							hint="constant">
							MY_STRING_CONSTANT
						</item>
						<item
							type="junitx.ddtunit.resources.SimpleConstants"
							hint="constant">
							MY_STRING_CONSTANT
						</item>
					</obj>
				</objs>
				<asserts>
					<assert id="count" type="int" action="isEqual">
						2
					</assert>
					<assert id="result"
						type="junitx.ddtunit.resources.SimpleConstants" action="isEqual"
						hint="constant">
						MY_STRING_CONSTANT
					</assert>
					<assert id="type" type="string" action="isEqual">
						java.util.Vector
					</assert>
				</asserts>
			</test>
		</group>
		<!--                                                                  -->
		<!-- Java 5 Enumeration validation                                    -->
		<!--                                                                  -->
		<group id="testJDK5Enumerator">
			<test id="myFirstTestCase">
				<objs>
					<obj id="enumer"
						type="junitx.ddtunit.resources.MyEnumerator" hint="constant">
						FIRST_ENUMERATION
					</obj>
				</objs>
				<asserts>
					<assert id="result"
						type="junitx.ddtunit.resources.MyEnumerator" hint="constant"
						action="isNotNull">
						FIRST_ENUMERATION
					</assert>
					<assert id="result1"
						type="junitx.ddtunit.resources.MyEnumerator" hint="constant"
						action="isNotEqual">
						SECOND_ENUMERATION
					</assert>
				</asserts>
			</test>
		</group>
		<group id="testEnumerationElement">
          <test id="setEnumByBeanDefinition">
            <objs>
              <obj id="myVO" type="junitx.ddtunit.resources.SimpleVOExtendByEnumerator"
                hint="bean">
                <stringValue type="string">Hello Enumerator</stringValue>
                <myEnum type="junitx.ddtunit.resources.MyEnumerator" hint="constant">
                   FIRST_ENUMERATION</myEnum>
              </obj> 
            </objs>
            <asserts>
              <assert id="result1" action="isNotNull" 
                type="junitx.ddtunit.resources.SimpleVOExtendByEnumerator"></assert>
              <assert id="result2" action="isEqual" type="junitx.ddtunit.resources.MyEnumerator"
                hint="constant">
                  FIRST_ENUMERATION</assert>
            </asserts>
          </test>
          <test id="setEnumByFieldDefinition">
            <objs>
              <obj id="myVO" type="junitx.ddtunit.resources.SimpleVOExtendByEnumerator">
                <stringValue type="string">Hello Enumerator</stringValue>
                <myEnum type="junitx.ddtunit.resources.MyEnumerator" hint="constant">
                   SECOND_ENUMERATION</myEnum>
              </obj> 
            </objs>
            <asserts>
              <assert id="result1" action="isNotNull" 
                type="junitx.ddtunit.resources.SimpleVOExtendByEnumerator"></assert>
              <assert id="result2" action="isEqual" type="junitx.ddtunit.resources.MyEnumerator"
                hint="constant">
                  SECOND_ENUMERATION</assert>
            </asserts>
          </test>
		</group>
	</cluster>
</ddtunit>

=== strohitv/ddtunit-fork/src/test/resources/junitx/ddtunit/optional/junit4/DDT-DDTJUnit4ClassRunnerTest.xml
<?xml version="1.0" ?>
<ddtunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="http://ddtunit.sourceforge.net/ddtunit.xsd">
  <cluster id="DDTJUnit4ClassRunnerTest">
    <!--                                                                  -->
    <!-- simple object retrieval                                          -->
    <!--                                                                  -->
    <group id="retrieveObjectData">
      <test id="myFirstTestCase">
        <objs>
          <obj id="myObj" type="java.lang.String">My first String</obj>
        </objs>
      </test>
      <test id="mySecondTestCase">
        <objs>
          <obj id="myObj" type="java.lang.String">My second String</obj>
        </objs>
      </test>
    </group>
    <!--                                                                  -->
    <!-- simple assert processing                                         -->
    <!--                                                                  -->
    <group id="testRetrieveAssertData">
      <test id="myFirstTestCase">
        <objs>
          <obj id="myObj" type="java.lang.String">My first String</obj>
        </objs>
        <asserts>
          <assert id="result" type="java.lang.String" action="isEqual">My first String</assert>
        </asserts>
      </test>
      <test id="mySecondTestCase">
        <objs>
          <obj id="myObj" type="java.lang.String">My second String</obj>
        </objs>
        <asserts>
          <assert id="result" type="java.lang.String" action="isNotEqual">
            My other String</assert>
        </asserts>
      </test>
    </group>
  </cluster>
</ddtunit>
